# This rule is not used by the project observability-gateway-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over observability.x-k8s.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: observability-gateway-operator
    app.kubernetes.io/managed-by: kustomize
  name: observabilitygateway-admin-role
rules:
- apiGroups:
  - observability.x-k8s.io
  resources:
  - observabilitygateways
  verbs:
  - '*'
- apiGroups:
  - observability.x-k8s.io
  resources:
  - observabilitygateways/status
  verbs:
  - get
