apiVersion: observability.x-k8s.io/v1alpha1
kind: ObservabilityGateway
metadata:
  labels:
    app.kubernetes.io/name: observability-gateway-operator
    app.kubernetes.io/managed-by: kustomize
  name: observabilitygateway-sample
spec:
  # TODO(user): Add fields here
